export const AccessData = [
  {
    key: "1",
    name: "MyraFoster",
    tag: "@myra",
    email: "myra@gmail.com",
    role: "Editor",
    plan: "Creator",
    status: "Active",
  },
  {
    key: "1",
    name: "MyraFoster",
    tag: "@myra",
    email: "myra@gmail.com",
    role: "Viewer",
    plan: "Creator",
    status: "Pending",
  },
  {
    key: "1",
    name: "MyraFoster",
    tag: "@myra",
    email: "myra@gmail.com",
    role: "Viewer",
    plan: "Free",
    status: "Inactive",
  },
  {
    key: "1",
    name: "MyraFoster",
    tag: "@myra",
    email: "myra@gmail.com",
    role: "Viewer",
    plan: "Creator",
    status: "active",
  },
  {
    key: "1",
    name: "MyraFoster",
    tag: "@myra",
    email: "myra@gmail.com",
    role: "Viewer",
    plan: "Creator",
    status: "active",
  },
  {
    key: "1",
    name: "MyraFoster",
    tag: "@myra",
    email: "myra@gmail.com",
    role: "Viewer",
    plan: "Creator",
    status: "active",
  },
  {
    key: "1",
    name: "MyraFoster",
    tag: "@myra",
    email: "myra@gmail.com",
    role: "Viewer",
    plan: "Creator",
    status: "active",
  },
  {
    key: "1",
    name: "MyraFoster",
    tag: "@myra",
    email: "myra@gmail.com",
    role: "Viewer",
    plan: "Creator",
    status: "active",
  },
  {
    key: "1",
    name: "MyraFoster",
    tag: "@myra",
    email: "myra@gmail.com",
    role: "Viewer",
    plan: "Creator",
    status: "active",
  },
  {
    key: "1",
    name: "MyraFoster",
    tag: "@myra",
    email: "myra@gmail.com",
    role: "Viewer",
    plan: "Creator",
    status: "active",
  },
  {
    key: "1",
    name: "MyraFoster",
    tag: "@myra",
    email: "myra@gmail.com",
    role: "Viewer",
    plan: "Creator",
    status: "active",
  },
  {
    key: "1",
    name: "MyraFoster",
    tag: "@myra",
    email: "myra@gmail.com",
    role: "Viewer",
    plan: "Creator",
    status: "active",
  },
  {
    key: "1",
    name: "MyraFoster",
    tag: "@myra",
    email: "myra@gmail.com",
    role: "Viewer",
    plan: "Creator",
    status: "active",
  },
  {
    key: "1",
    name: "MyraFoster",
    tag: "@myra",
    email: "myra@gmail.com",
    role: "Viewer",
    plan: "Creator",
    status: "active",
  },
  {
    key: "1",
    name: "MyraFoster",
    tag: "@myra",
    email: "myra@gmail.com",
    role: "Viewer",
    plan: "Creator",
    status: "active",
  },
  {
    key: "1",
    name: "MyraFoster",
    tag: "@myra",
    email: "myra@gmail.com",
    role: "Viewer",
    plan: "Creator",
    status: "active",
  },
  {
    key: "1",
    name: "MyraFoster",
    tag: "@myra",
    email: "myra@gmail.com",
    role: "Viewer",
    plan: "Creator",
    status: "active",
  },
  {
    key: "1",
    name: "MyraFoster",
    tag: "@myra",
    email: "myra@gmail.com",
    role: "Viewer",
    plan: "Creator",
    status: "active",
  },
  {
    key: "1",
    name: "MyraFoster",
    tag: "@myra",
    email: "myra@gmail.com",
    role: "Viewer",
    plan: "Creator",
    status: "active",
  },
  {
    key: "1",
    name: "MyraFoster",
    tag: "@myra",
    email: "myra@gmail.com",
    role: "Viewer",
    plan: "Creator",
    status: "active",
  },
  {
    key: "1",
    name: "MyraFoster",
    tag: "@myra",
    email: "myra@gmail.com",
    role: "Viewer",
    plan: "Creator",
    status: "active",
  },
  {
    key: "1",
    name: "MyraFoster",
    tag: "@myra",
    email: "myra@gmail.com",
    role: "Viewer",
    plan: "Creator",
    status: "active",
  },
  {
    key: "1",
    name: "MyraFoster",
    tag: "@myra",
    email: "myra@gmail.com",
    role: "Viewer",
    plan: "Creator",
    status: "active",
  },
  {
    key: "1",
    name: "MyraFoster",
    tag: "@myra",
    email: "myra@gmail.com",
    role: "Viewer",
    plan: "Creator",
    status: "active",
  },
  {
    key: "1",
    name: "MyraFoster",
    tag: "@myra",
    email: "myra@gmail.com",
    role: "Viewer",
    plan: "Creator",
    status: "active",
  },
  {
    key: "1",
    name: "MyraFoster",
    tag: "@myra",
    email: "myra@gmail.com",
    role: "Viewer",
    plan: "Creator",
    status: "active",
  },
  {
    key: "1",
    name: "MyraFoster",
    tag: "@myra",
    email: "myra@gmail.com",
    role: "Viewer",
    plan: "Creator",
    status: "active",
  },
  {
    key: "1",
    name: "MyraFoster",
    tag: "@myra",
    email: "myra@gmail.com",
    role: "Viewer",
    plan: "Creator",
    status: "active",
  },
  {
    key: "1",
    name: "MyraFoster",
    tag: "@myra",
    email: "myra@gmail.com",
    role: "Viewer",
    plan: "Creator",
    status: "active",
  },
  {
    key: "1",
    name: "MyraFoster",
    tag: "@myra",
    email: "myra@gmail.com",
    role: "Viewer",
    plan: "Creator",
    status: "active",
  },
  {
    key: "1",
    name: "MyraFoster",
    tag: "@myra",
    email: "myra@gmail.com",
    role: "Viewer",
    plan: "Creator",
    status: "active",
  },
  {
    key: "1",
    name: "MyraFoster",
    tag: "@myra",
    email: "myra@gmail.com",
    role: "Viewer",
    plan: "Creator",
    status: "active",
  },
  {
    key: "1",
    name: "MyraFoster",
    tag: "@myra",
    email: "myra@gmail.com",
    role: "Viewer",
    plan: "Creator",
    status: "active",
  },
  {
    key: "1",
    name: "MyraFoster",
    tag: "@myra",
    email: "myra@gmail.com",
    role: "Viewer",
    plan: "Creator",
    status: "active",
  },
  {
    key: "1",
    name: "MyraFoster",
    tag: "@myra",
    email: "myra@gmail.com",
    role: "Viewer",
    plan: "Creator",
    status: "active",
  },
  {
    key: "1",
    name: "MyraFoster",
    tag: "@myra",
    email: "myra@gmail.com",
    role: "Viewer",
    plan: "Creator",
    status: "active",
  },
  {
    key: "1",
    name: "MyraFoster",
    tag: "@myra",
    email: "myra@gmail.com",
    role: "Viewer",
    plan: "Creator",
    status: "active",
  },
  {
    key: "1",
    name: "MyraFoster",
    tag: "@myra",
    email: "myra@gmail.com",
    role: "Viewer",
    plan: "Creator",
    status: "active",
  },
  {
    key: "1",
    name: "MyraFoster",
    tag: "@myra",
    email: "myra@gmail.com",
    role: "Viewer",
    plan: "Creator",
    status: "active",
  },
  {
    key: "1",
    name: "MyraFoster",
    tag: "@myra",
    email: "myra@gmail.com",
    role: "Viewer",
    plan: "Creator",
    status: "active",
  },
  {
    key: "1",
    name: "MyraFoster",
    tag: "@myra",
    email: "myra@gmail.com",
    role: "Viewer",
    plan: "Creator",
    status: "active",
  },
  {
    key: "1",
    name: "MyraFoster",
    tag: "@myra",
    email: "myra@gmail.com",
    role: "Viewer",
    plan: "Creator",
    status: "active",
  },
  {
    key: "1",
    name: "MyraFoster",
    tag: "@myra",
    email: "myra@gmail.com",
    role: "Viewer",
    plan: "Creator",
    status: "active",
  },
  {
    key: "1",
    name: "MyraFoster",
    tag: "@myra",
    email: "myra@gmail.com",
    role: "Viewer",
    plan: "Creator",
    status: "active",
  },
  {
    key: "1",
    name: "MyraFoster",
    tag: "@myra",
    email: "myra@gmail.com",
    role: "Viewer",
    plan: "Creator",
    status: "active",
  },
  {
    key: "1",
    name: "MyraFoster",
    tag: "@myra",
    email: "myra@gmail.com",
    role: "Viewer",
    plan: "Creator",
    status: "active",
  },
  {
    key: "1",
    name: "MyraFoster",
    tag: "@myra",
    email: "myra@gmail.com",
    role: "Viewer",
    plan: "Creator",
    status: "active",
  },
  {
    key: "1",
    name: "MyraFoster",
    tag: "@myra",
    email: "myra@gmail.com",
    role: "Viewer",
    plan: "Creator",
    status: "active",
  },
];
